# Docker Compose configuration for the morphic-stack development environment

name: morphic-stack
services:
  morphic:
    image: ghcr.io/Peterfish/morphic-custom:latest
    command: bun start -H 0.0.0.0
    env_file: .env.local
    ports:
      - '3030:3000'
    depends_on:
      - redis
      - searxng

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  searxng:
    image: searxng/searxng
    ports:
      - '${SEARXNG_PORT:-8080}:8080'
    env_file: .env.local
    volumes:
      - ./searxng-limiter.toml:/etc/searxng/limiter.toml
      - ./searxng-settings.yml:/etc/searxng/settings.yml
      - searxng_data:/data

volumes:
  redis_data:
  searxng_data: